CREATE DATABASE artgallery;
\c artgallery;

CREATE TABLE GALLERY
(GID VARCHAR(20) PRIMARY KEY,
GNAME CHAR(20),
LOCATION VARCHAR(30));

CREATE TABLE EXHIBITION
(EID VARCHAR(10) PRIMARY KEY,
GID VARCHAR(20),
STARTDATE DATE,
ENDDATE DATE,
FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE CASCADE);

CREATE TABLE ARTWORK
(ARTID VARCHAR(10) PRIMARY KEY,
TITLE VARCHAR(20),
YEAR INT,
TYPE_OF_ART VARCHAR(20),
PRICE INT,
A_EID VARCHAR(10), A_GID VARCHAR(20),
FOREIGN KEY(A_EID) REFERENCES EXHIBITION(EID) ON DELETE CASCADE,
FOREIGN KEY(A_GID) REFERENCES GALLERY(GID) ON DELETE CASCADE);

CREATE TABLE CUSTOMER 
(CUSTID VARCHAR(10) PRIMARY KEY,
C_GID VARCHAR(20),
C_ARTID VARCHAR(10),
FNAME CHAR(20),
LNAME CHAR(20),
DOB DATE,
ADDRESS CHAR(20),
FOREIGN KEY(C_GID) REFERENCES GALLERY(GID) ON DELETE CASCADE,
FOREIGN KEY(C_ARTID) REFERENCES ARTWORK(ARTID) ON DELETE CASCADE);

CREATE TABLE ARTIST
(ARTISTID VARCHAR(20) PRIMARY KEY,
AR_GID VARCHAR(20),
AR_CUSTID VARCHAR(10),
AR_EID VARCHAR(10),
A_FNAME CHAR(20),
A_LNAME CHAR(20),
BIRTHPLACE CHAR(20),
STYLE CHAR(20),
FOREIGN KEY(AR_GID) REFERENCES GALLERY(GID) ON DELETE CASCADE,
FOREIGN KEY (AR_CUSTID) REFERENCES CUSTOMER(CUSTID) ON DELETE CASCADE,
FOREIGN KEY(AR_EID) REFERENCES EXHIBITION(EID) ON DELETE CASCADE);

ALTER TABLE ARTWORK ADD A_ARTISTID VARCHAR(20);
ALTER TABLE ARTWORK
ADD FOREIGN KEY (A_ARTISTID) REFERENCES ARTIST(ARTISTID) ON DELETE CASCADE;

CREATE TABLE CONTACTS
(C_CUSTID VARCHAR(20),
PHONE_NO VARCHAR(12),
FOREIGN KEY (C_CUSTID) REFERENCES CUSTOMER(CUSTID) ON DELETE 
CASCADE);



